Add interface
oJieg/test1 pull request #4
Opened 2022-03-27 17:21 UTC by oJieg

2022-03-27 18:17 UTC, Orygeunik requested changes
Есть некоторые замечания

2022-03-27 18:17 UTC, Orygeunik commented on BaseDataContactsSQL.cs
> +    /// первым делом вызови InitializationBD
Если нужно что-то обязательно сделать - кидают явно ошибку, что не был вызван метод "конфигурации", ибо целевое описание могут и заигнорить

2022-03-27 18:17 UTC, Orygeunik commented on BaseDataContactsSQL.cs
> +        private string _dataSourceBD = "";
Лучше использовать так:
```suggestion
        private string _dataSourceBD = string.Empty;
```

2022-03-27 18:17 UTC, Orygeunik commented on BaseDataContactsSQL.cs
> +        /// nameFile - имя файла без разширения. В случаи не допустимого имени, вернет false.
А что будет, если кто-то передаст с расширением? Может быть стоит это валидировать?

2022-03-27 18:17 UTC, Orygeunik commented on BaseDataContactsSQL.cs
> +            string forbiddenSymbols = new(Path.GetInvalidFileNameChars());
У тебя этот код повторяется, в классе `BaseDataContactsCSV.cs`, может быть обхединить?

2022-03-27 18:17 UTC, Orygeunik commented on BaseDataContactsSQL.cs
> +                return false;
Тут есть проблема, что у тебя ошибка "проглатывается" и пользователь, не узнает в чем дело
тут бы хоть как-то сообщать о проблеме)

2022-03-27 18:17 UTC, Orygeunik commented on BaseDataContactsSQL.cs
> +        public bool TryAddContact(string name, string? phone)
Смотри какой хитрый момент получился
У тебя правила валидации для базы и для CSV - различны, т.е. если условно будет импортирование из базы в CSV - все сломается

2022-03-27 18:17 UTC, Orygeunik commented on BaseDataContactsSQL.cs
> +                    outContacts.Add(new Contact(reader.GetString("Name"), reader.GetString("phone")));
Соблюдай то как указано имя в селекте и тут. Некоторые БД критичны к регистру
```suggestion
                    outContacts.Add(new Contact(reader.GetString("Name"), reader.GetString("Phone")));
```

2022-03-27 18:17 UTC, Orygeunik commented on BaseDataContactsTemporary .cs
> +
Тут лишняя строка, а между 8 и 9 - её нет)

2022-03-27 18:17 UTC, Orygeunik commented on BaseDataContactsTemporary .cs
> +                if (string.IsNullOrWhiteSpace(phone))
А что если вот эту логику "скрыть" внутри самого `Contact` - класса? Зачем вызывающему коду знать о его деталях?

2022-03-27 18:17 UTC, Orygeunik commented on ChoiceOfRecordingMethod.cs
> +            Console.WriteLine("1-из ОЗУ(данные стираются после работы");
```suggestion
            Console.WriteLine("1-из ОЗУ (данные стираются после работы)");
```

2022-03-27 18:17 UTC, Orygeunik commented on ChoiceOfRecordingMethod.cs
> +                name += Console.ReadLine();
А почему у тебя тут:
```
 string name = "";
name += Console.ReadLine();
```
Почему нельзя сразу `sting name =  Console.ReadLine()`?

Более того, у тебя вся соль переменной, чтобы передать её в метод `TryInitializationBD`, можно сразу даже так:
`TryInitializationBD(Console.ReadLine())`

2022-03-27 18:48 UTC, oJieg commented on BaseDataContactsCSV.cs
> +            if (input == null)
Телефон может быть null.

2022-03-28 17:17 UTC, oJieg commented on BaseDataContactsCSV.cs
> +        public bool TryInitializationBD(string nameFile)
Это от слова bazaBannix) исправил)

2022-03-28 17:22 UTC, oJieg commented on BaseDataContactsCSV.cs
> +                if (r.Match(nameFile).Success)
Логично, тогда только если 2 предыдущих варианта не вышли, тогда только вернёт ошибку

2022-03-28 17:26 UTC, oJieg commented on BaseDataContactsCSV.cs
> +
Ок

2022-03-28 17:29 UTC, oJieg commented on BaseDataContactsCSV.cs
> +            System.Text.Encoding.RegisterProvider(System.Text.CodePagesEncodingProvider.Instance);
Самый прикол он и так был подключен) просто лишние строчки.

2022-03-28 17:33 UTC, oJieg commented on BaseDataContactsCSV.cs
> +                    if (i >= offset && i < take + offset)
Ок

2022-03-28 18:04 UTC, oJieg commented on BaseDataContactsCSV.cs
> +        private static string DeliteEscape(string wold)
Боюсь тут не поможет, все равно придется переписывать,ибо экран нужно снимать и с других символов, перепишу этот метод

2022-03-28 19:04 UTC, oJieg commented on BaseDataContactsCSV.cs
> +            Regex r = new("[^;]+");
Принял

2022-03-28 19:14 UTC, oJieg commented on BaseDataContactsSQL.cs
> +        private string _dataSourceBD = "";
Поправил

2022-03-29 19:23 UTC, Orygeunik commented on BaseDataContactsCSV.cs
> +            if (input == null)
А что насчет имени контакта?

2022-03-29 19:23 UTC, Orygeunik commented on IDataContactInterface.cs
> +        bool TryInitializationDB(string nameFile);
А почему в общем интерфейсе есть привязка к базе данных? Может стоит просто `TryInitialization`?

2022-03-30 09:29 UTC, oJieg commented on BaseDataContactsSQL.cs
> +    /// первым делом вызови InitializationBD
Не очень понимаю как это сделать, разве что валидацию на каждый метод прихерачить. Именно по этому я изначально делал иниацилизацию в конструкторе, но Евгений сказал так не верно делать( 
Короче запутался я опять с тем "как правильно" делать классы.

2022-03-30 09:30 UTC, oJieg commented on BaseDataContactsSQL.cs
> +        /// nameFile - имя файла без разширения. В случаи не допустимого имени, вернет false.
А в чем проблема? ну будет test.csv.csv вполне себе допустимое название файла же.

2022-03-30 11:41 UTC, oJieg commented on BaseDataContactsSQL.cs
> +            string forbiddenSymbols = new(Path.GetInvalidFileNameChars());
Добавил дополнительный класс.

2022-03-30 11:46 UTC, oJieg commented on BaseDataContactsSQL.cs
> +                return false;
Разве что в консоль можно вывести ошибку,

2022-03-30 12:08 UTC, oJieg commented on BaseDataContactsSQL.cs
> +        public bool TryAddContact(string name, string? phone)
Вынес валидацию в другой класс.

2022-03-30 12:10 UTC, oJieg commented on BaseDataContactsSQL.cs
> +                    outContacts.Add(new Contact(reader.GetString("Name"), reader.GetString("phone")));
Поправил

2022-03-30 13:07 UTC, oJieg commented on BaseDataContactsCSV.cs
> +        private static string DeliteEscape(string wold)
Да, trim хорошая штука) метод поправил.

2022-03-30 13:10 UTC, oJieg commented on ChoiceOfRecordingMethod.cs
> +            Console.WriteLine("1-из ОЗУ(данные стираются после работы");
) исправил

2022-03-30 13:25 UTC, oJieg commented on ChoiceOfRecordingMethod.cs
> +                name += Console.ReadLine();
хотел так обойти обойти ошибку о null

2022-03-30 14:21 UTC, oJieg commented on BaseDataContactsCSV.cs
> +        private string _nameFile = String.Empty;
ok)

2022-03-30 14:21 UTC, oJieg commented on BaseDataContactsCSV.cs
> +        private Regex _separatorChar = new("[^;]+", RegexOptions.Compiled);
ok

2022-03-30 14:25 UTC, oJieg commented on IDataContactInterface.cs
> +        bool TryInitializationDB(string nameFile);
Ну так все же интерфейс про базы данных, нет?

2022-04-01 15:06 UTC, Orygeunik commented on BaseDataContactsSQL.cs
> +                return false;
Можно познакомится с логами, если ты готов к этому)

2022-04-01 15:19 UTC, Orygeunik commented on BaseDataContactsCSV.cs
> +            return ValidationImputClass.TryValidatoinNameFile(nameFile, out _nameFile);
```suggestion
            return ValidationInputClass.TryValidatoinNameFile(nameFile, out _nameFile);
```
От слова In - put, т.е. по сути "засунуть"

2022-04-01 15:19 UTC, Orygeunik commented on ValidationImput.cs
> +        public static bool TryValidatoinNameFile(string? nameFile, out string fullNameFile)
```suggestion
        public static bool TryValidationNameFile(string? nameFile, out string fullNameFile)
```

2022-04-01 15:19 UTC, Orygeunik commented on ValidationImput.cs
> +            correctInput= _validationSeparatorChar.Match(inputName).Success;
Форматирование

2022-04-01 15:19 UTC, Orygeunik commented on ValidationImput.cs
> +            if (nameFile == string.Empty || nameFile == null)
Для этих целей есть `string.IsNullOrWhiteSpace`
делает почти тоже самое, но правильно :)

2022-04-01 15:19 UTC, Orygeunik commented on ChoiceOfRecordingMethod.cs
> +            Console.WriteLine("1-из ОЗУ (данные стираются после работы");
```suggestion
            Console.WriteLine("1-из ОЗУ (данные стираются после работы)");
```

2022-04-01 15:19 UTC, Orygeunik commented on ChoiceOfRecordingMethod.cs
> +                    case 1: return InitializationBDName(new BaseDataContactsTemporary());
Копипаст!
Аааа
Попробуй избавится от него, если не получится подскажу чуть получше

2022-04-01 15:19 UTC, Orygeunik commented on BaseDataContactsTemporary .cs
> +                if (string.IsNullOrWhiteSpace(phone))
Ап

2022-04-01 15:19 UTC, Orygeunik commented on BaseDataContactsCSV.cs
> +            if(line[0] == ';')
Форматирование

2022-04-16 12:38 UTC, oJieg commented on BaseDataContactsCSV.cs
> +            return ValidationImputClass.TryValidatoinNameFile(nameFile, out _nameFile);
поправил

2022-04-16 12:39 UTC, oJieg commented on ValidationImput.cs
> +        public static bool TryValidatoinNameFile(string? nameFile, out string fullNameFile)
ок

2022-04-16 12:40 UTC, oJieg commented on ValidationImput.cs
> +            if (nameFile == string.Empty || nameFile == null)
хорошо, поправил в похожем месте

2022-04-16 12:41 UTC, oJieg commented on ChoiceOfRecordingMethod.cs
> +            Console.WriteLine("1-из ОЗУ (данные стираются после работы");
Добавил

2022-04-16 12:41 UTC, oJieg commented on ChoiceOfRecordingMethod.cs
> +                    case 1: return InitializationBDName(new BaseDataContactsTemporary());
не решил эту проблему, подскажи)

2022-04-16 12:42 UTC, oJieg commented on BaseDataContactsCSV.cs
> +            if(line[0] == ';')
поправил

2022-04-16 15:40 UTC, Orygeunik requested changes
Есть что исправить + обсуждения из дискорда

2022-04-16 15:40 UTC, Orygeunik commented on BaseDataContactsCSV.cs
> +            {
Ошибка так же "пропадает" не есть торт

2022-04-16 15:40 UTC, Orygeunik commented on BaseDataContactsCSV.cs
> +            if (word == null)
А тут точно только null может быть? Каких-нибудь "пустых строк" или "пробельных нету"?
Если есть то `string.IsNullOrWhiteSpace()`

2022-04-16 15:40 UTC, Orygeunik commented on BaseDataContactsSQL.cs
> +                //логи
Не похоже :)

2022-04-16 15:40 UTC, Orygeunik commented on BaseDataContactsTemporary .cs
> +                if (string.IsNullOrWhiteSpace(phone))
снова апаю тему

2022-04-16 15:40 UTC, Orygeunik commented on Program.cs
> +            Screen screenChoise = new ScreenChoise(3);
```suggestion
            Screen screenChoiсe = new ScreenChoiсe(3);
```
https://translate.google.com/?sl=en&tl=ru&text=choice&op=translate

2022-04-16 15:40 UTC, Orygeunik commented on Screen.cs
> +        protected void FullAmoutOfLine()
```suggestion
        protected void FullAmountOfLines()
```

2022-04-16 15:40 UTC, Orygeunik commented on Screen.cs
> +        protected virtual void ChoiseInpyt(int inputInt, string inputString)
```suggestion
        protected virtual void ChoiceInput(int inputInt, string inputString)
```

2022-04-16 15:40 UTC, Orygeunik commented on Screen.cs
> +            InputString = kay.Key.ToString();
А зачем ты из enum-а кастишь в стрингу?
Сразу enum проверяй

https://docs.microsoft.com/ru-ru/dotnet/api/system.consolekey?view=net-6.0

2022-04-16 15:40 UTC, Orygeunik commented on Screen.cs
> +        protected virtual void Title()
Абстракт?

2022-04-16 15:40 UTC, Orygeunik commented on ScreenChoise.cs
> +                ScreenFileSelection fileSelector = new ScreenFileSelection(2, formatFile);
Число 2 - внезапное, лучше такие вещи в константы класть, они хотя бы описывают, что такое "два"

2022-04-16 15:40 UTC, Orygeunik commented on ScreenFileSelection.cs
> +            if (!Directory.Exists(@"\DataBase"))
Эм.. .а куда этот путь указывает?

2022-04-16 15:40 UTC, Orygeunik commented on ValidationInput.cs
> +                //File.Create($"{nameFile}.csv").Close();
Тут что-то как будто из нет

2022-04-16 15:40 UTC, Orygeunik commented on ValidationInput.cs
> +            if(inputPhone != null && correctInput)
А если `inputPhone` пустая строка?

2022-04-18 06:33 UTC, oJieg commented on Screen.cs
> +        protected virtual void Title()
А если мне нужен заголовок? Пускай уж дефолтный вариант будет пустым

2022-05-01 18:33 UTC, Orygeunik requested changes
Есть некоторые замечания.
И это не считая косяков в русском (так же приведи логги и записи на экране к одному виду)

2022-05-01 18:33 UTC, Orygeunik commented on BaseDataContactsCSV.cs
> +                _logger.LogError(ex, "Ошибка иниацилизации BaseDataContactsCSV");
Не крит.
Проверь опечатки во втором слове

2022-05-01 18:33 UTC, Orygeunik commented on BaseDataContactsCSV.cs
> +        public BaseDataContactsCSV(ILogger logger)
Рекомендую использовать ILogger<T>, где T - класс в котором ты используешь логгер. Это позволит в логи автоматически писать имя класса (сам логгер это будет делать)

2022-05-01 18:33 UTC, Orygeunik commented on BaseDataContactsCSV.cs
> +                Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
Как уже ранее писал, это достаточно 1 раз сделать. Тебе не надо регистрировать каждый раз, как ты пытаешься получить контакт

2022-05-01 18:33 UTC, Orygeunik commented on BaseDataContactsCSV.cs
> +    && !File.Exists(fullName))
Форматирование поломалось

2022-05-01 18:33 UTC, Orygeunik commented on BaseDataContactsCSV.cs
> +                    File.Create(fullName).Close();
В итоге все-равно решил момент с созданием пустого файла, а потом заново его открывать?

2022-05-01 18:33 UTC, Orygeunik commented on BaseDataContactsSQL.cs
> +                Path.Combine(Directory.GetCurrentDirectory(), directory, $"{nameFile}.db")) &&
`Path.Combine() && ValidationInputClass.TryValidatinNameFile(nameFile)` - лучше вынести как отдельный шаг, с результатом в отдельную пельменную, ибо я долго пытался понять, что тут происходит

2022-05-01 18:33 UTC, Orygeunik commented on BaseDataContactsSQL.cs
> +        public string FormatFile()
Можно как свойство, а не метод сделать

2022-05-01 18:33 UTC, Orygeunik commented on BaseDataContactsTemporary .cs
> +            if (offset < 0 || offset > amoutOfContact)
У тебя блок проверки границ, во всех наследниках одинаковый, можно было бы сделать как единый метод :)

2022-05-01 18:33 UTC, Orygeunik commented on BaseDataContactsTemporary .cs
> +    "{offset}, {take}-количество элементов.", offset, take);
Форматирование поехало

2022-05-01 18:33 UTC, Orygeunik commented on BaseDataContactsTemporary .cs
> +                    outContacts.Add(contact);
Там есть метод AddRange у List<T> можно упростить

2022-05-01 18:33 UTC, Orygeunik commented on NLog.config
> +  <!-- optional, add some variables
Не крит
Можно было бы потереть коменты все лишние

2022-05-01 18:33 UTC, Orygeunik commented on Screen.cs
> +        protected void FullAmoutOfLine()
ап

2022-05-01 18:33 UTC, Orygeunik commented on Screen.cs
> +            InputString = key.Key.ToString();
Тебе нет смысла кастовать Enum к строке, а потом сравнивать строку. Сразу сравнивай Enum

2022-05-01 18:33 UTC, Orygeunik commented on ScreenFileSelection.cs
> +            catch (IndexOutOfRangeException ex)
Формально это твоя ошибка, ты же можешь проверить, что ты попадаешь "в границы"

2022-05-01 18:33 UTC, Orygeunik commented on ScreenFileSelection.cs
> +                Logger.LogCritical(ex, "ошибка получения списка для рендера его.");
Не крит
Предложение не согласованным выглядит

2022-05-01 18:33 UTC, Orygeunik commented on ScreenFileSelection.cs
> +        private readonly string fullAdresDirectory;
```suggestion
        private readonly string fullAddressDirectory;
```

2022-05-01 18:33 UTC, Orygeunik commented on ScreenFileSelection.cs
> +            nameFile += Console.ReadLine();
А зачем сначала создать пустую строку, а потом к ней приплюсовать ввод от пользователя? Можно было сразу в пельменную положить

2022-05-01 18:33 UTC, Orygeunik commented on ScreenMainBD.cs
> +        "в имени или телефоне есть запрешенные символы name - {name}, phone - {phone}", name, phone);
Если что, буква ЩА и буква ША - это две разные буквы

2022-05-01 18:33 UTC, Orygeunik commented on ScreenSelect.cs
> +                        new(NumberOfLinesOnRender, new BaseDataContactsTemporary(Logger), Logger);
А почему ты кидаешь уже логгер, который создан для Program в каждый класс?
У тебя должны создаваться для каждого класса свой логгер, из фабрики
Т.е. делать примерно такое
`loggerFabric.CreateLogger<BaseDataContactsTemporary>()`

2022-05-01 18:33 UTC, Orygeunik commented on ValidationInput.cs
> +            if (nameFile == string.Empty || nameFile == null)
String.IsNullOrWhiteSpace для этого следует юзать

2022-05-15 18:44 UTC, Orygeunik approved these changes
Принимаю, с мелкими недочетами

2022-05-15 18:44 UTC, Orygeunik commented on BaseDataContactsCSV.cs
>              _logger = loggerFactory.CreateLogger<BaseDataContactsCSV>();
Заметка на будущее, тут можно было упростить
Поскольку ты вызываешь его так
`new  BaseDataContactsCSV(LoggerFactory)`
Можно проще было написать
` new  BaseDataContactsCSV(LoggerFactory..CreateLogger<BaseDataContactsCSV>)`

Т.е. сразу передать ILogger<T>

2022-05-15 18:44 UTC, Orygeunik commented on BaseDataContactsCSV.cs
> +                    File.Create(nameFile).Close();
Избыточно
Можно опустить
Все методы записи, могут создать файл, если его нет

2022-05-15 18:49 UTC, merged